### PR TITLE
fix: Bad function import

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Why? https://github.com/victorpoluceno/xwing/blob/development/xwing/mailbox/__init__.py#L126

**Comment by victorpoluceno** [comment]
@mauricioabreu I want the API to be as clean as possible, so just functions, not class. Do you have any ideas on how to improve that?

**Comment by victorpoluceno** [comment]
@mauricioabreu I gonna merge this any way...

**Comment by mauricioabreu** [comment]
I have :) Let me think about it so I can open a good issue for this.

**Pull request merged**
